# Site settings
author: Kevin J Gomez
title: The fun aches of CLI with Scraper
header-img: img/home-bg.png
email: kjgmez1@gmail.com
copyright_name: Kevin J Gomez
description: > # this means to ignore newlines until "baseurl:"
  How I created the CLI and OO interactions and logic
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kjgmez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
